apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-deployment
  labels:
    name: redis-primary
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: redis-primary
  serviceName: "redis-svc"
  template:
    metadata:
      labels:
        app: redis-primary
    spec:
      subdomain: primary
      # Assign to redis-pool nodepool
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - redis-pool 
      containers:
      - name: redis
        image: redislabs/redismod
        command:
          - "redis-server"
        args:
          - "--protected-mode"
          - "no"
        ports:
        - containerPort: 6379
        # volumeMounts:
        #   - mountPath: /data
        #     name: redis-data
        volumeMounts:
          - mountPath: "/data"
            name: task-pv-storage
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis-svc
  selector:
    app: redis-primary