# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caching-deployment
  labels:
    app: caching
spec:
  replicas: 3
  selector:
    matchLabels:
      app: caching
  template:
    metadata:
      labels:
        app: caching
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                  - default-pool
      containers:
        - name: caching
          image: us-central1-docker.pkg.dev/amore-f8cd6/amore-microservices/caching-api:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 5050
          env:
            - name: FIREBASE_CRED
              valueFrom:
                secretKeyRef:
                  name: firebase-secret
                  key: serviceAccountKey.json


---
apiVersion: v1
kind: Service
metadata:
  name: caching-service
spec:
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: caching