# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caching-deployment
  labels:
    app: caching
spec:
  replicas: 3
  selector:
    matchLabels:
      app: caching
  template:
    metadata:
      labels:
        app: caching
    spec:
      containers:
        - name: caching
          image: caching-api
          imagePullPolicy: Never
          ports:
            - containerPort: 5050


---
apiVersion: v1
kind: Service
metadata:
  name: caching-service
spec:
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: caching