FROM python:3.9-slim-buster
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
WORKDIR /code
COPY . /code
RUN pip3 install -r requirements.txt --no-cache-dir
EXPOSE 80
ENTRYPOINT python MessagingService/RecentChatService.py