apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: amore_caching
build: 	
  artifacts: 
    - image: us-central1-docker.pkg.dev/amore-f8cd6/amore-microservices/caching-api:tag1 
      context: .
      docker:
        dockerfile: "Dockerfile"
deploy: 	
  kubectl: 	
    manifests: 	
      - "deployment.yaml"