# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
    # Assign to redis-pool nodepool
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - redis-pool 
      containers:
        - name: notification
          image: us-central1-docker.pkg.dev/amore-f8cd6/amore-microservices/notification:latest
          # imagePullPolicy: Never
          env:
            - name: FIREBASE_CRED
              valueFrom:
                secretKeyRef:
                  name: firebase-secret
                  key: stagingServiceAccountKey.json
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: notification-service
  selector:
    app: notification