apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-deployment
  labels:
    name: redis-primary
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: redis-primary
  serviceName: "redis-svc"
  template:
    metadata:
      labels:
        app: redis-primary
    spec:
      subdomain: primary
      containers:
      - name: redis
        image: redislabs/redisearch
        resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "250m"
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: "/data"
            name: task-pv-storage
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis-svc
  selector:
    app: redis-primary