name: Deploy Notification to GKE
on:
  workflow_dispatch:
jobs:
  deploy-to-gke:
      needs: build-push-gcr
      runs-on: ubuntu-latest
      env: 
        USE_GKE_GCLOUD_AUTH_PLUGIN: true

      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
            install_components: 'gke-gcloud-auth-plugin'
            export_default_credentials: true

      - name: 'Install gke-gcloud-auth-plugin'
        run: 'gcloud components install gke-gcloud-auth-plugin'

  #     - name: 'get-credentials'
  #       uses: 'google-github-actions/get-gke-credentials@v1'
  #       with:
  #         cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
  #         location: 'us-central1'
  #         project_id: ${{ secrets.PROJECT_ID }}
  #         use_auth_provider: true

      - name: kubectl - Google Cloud GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.COMPUTE_ENGINE_SA_KEY }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: ${{ secrets.ZONE_NAME }}
        with:
          args: apply -f NotificationService/deployment.yaml
